### ISSUE TITLE
how to excute?

### ISSUE THREAD

**Issue by Lollypo** [4Lang/4#17]
if i wrote a program file,how can i excute it?,tks.

**Comment by Lollypo** [comment]
i found a bat file.it's can excute on osx?

**Comment by qezz** [comment]
Command in bat-file is:
```bash
g++ main.cpp -std=c++11 -o 4c -Wall -Wextra -pedantic
```
So if u have g++ installed in your OSX, u can use command line to execute it

**Comment by Lollypo** [comment]
@qezz tks,but after i except this,i got this error on my OS X 10.10.3
```
└[~/Desktop/LHG/4/4c]> g++ main.cpp -std=c++11 -o 4c -Wall -Wextra -pedantic
In file included from main.cpp:2:
In file included from ./lexer/lexer.hpp:36:
In file included from ./lexer/lexer.inl:1:
./lexer/emoji.hpp:38:15: error: no template named 'unordered_set'; did you mean
      'std::unordered_set'?
        static const unordered_set<CharT> emojis = {
                     ^~~~~~~~~~~~~
                     std::unordered_set
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/unordered_set:338:29: note: 
      'std::unordered_set' declared here
class _LIBCPP_TYPE_VIS_ONLY unordered_set
                            ^
1 error generated.
```

**Comment by nv-vn** [comment]
@Lollypo try adding `using namespace std;` to the top of the file or replacing all occurrences of `unordered_set` with `std::unordered_set`.

**Comment by Lollypo** [comment]
tks,i add `using namespace std;` to the `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/unordered_set` file's top. then can generate a 4c file.i use it to execute other ***.4c** source code.
 it works well

**Comment by FourMan** [comment]
This has been fixed by adding the std:: prefix to the unordered_set
